version: '3.8'

services:
  monitor:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - IMAP_SERVER=${IMAP_SERVER:-br188.hostgator.com.br}
      - IMAP_PORT=${IMAP_PORT:-993}
      - IMAP_USER=${IMAP_USER:-sooretama@megasec.com.br}
      - IMAP_PASSWORD=${IMAP_PASSWORD:-Megasec@2025}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-8002419840:AAFL_Wu0aZ_NOGS9LOo9a9HxRbdGMxxv6-E}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-1395823978}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs:rw  # Mantendo logs para monitoramento
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongodb_data:
  mongodb_config:

networks:
  wegnots-network:
    driver: bridge
